### PR TITLE
simplified parser

### PR DESCRIPTION
**Pull request by arcturus5340**
Incomplete simplification of the program

### CODE REVIEW

**Comment by LivingTribunal18** [comment]
why did you clear tmp_list and tmp_tokens?
(line 93)

**Comment by LivingTribunal18** [comment]
why you have an isDigit variable declared as an integrator, and then assign the result of the isdigit function to this variable, but the isdigit function returns only true or false
(function isLiteral)

**Comment by LivingTribunal18** [comment]
Why did you use keywords? Our syntax does not yet use this.
(function push)

**Comment by arcturus5340** [comment]
> why did you clear tmp_list and tmp_tokens?
> (line 93)

Without this, each new command block will contain the values of the old

> why you have an isDigit variable declared as an integrator, and then assign the result of the isdigit function to this variable, but the isdigit function returns only true or false
> (function isLiteral)

С-Magic. There is no bool in c
`typedef int bool;`
`#define true 1`
`#define false 0`
bool is int. This is just old hack. Everything that is not 0 is true (1 in most cases)

> Why did you use keywords? Our syntax does not yet use this.
> (function push)

Soon there will be conditions. I understood this in the previous code

**Pull request merged**
